name: Lint Check & Test
on: [pull_request]
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        node_version:
          - 14
          - 16
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          check-latest: true
          cache: 'npm'
      - name: upgrade npm
        run: npm i -g npm@^8.1.4

      - name: Install Dependencies
        run: npm ci

      - name: Lint Check & Test
        run: npm run ci
