name: Lint Check & Test
on: [pull_request]
jobs:
  lint:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Check & Test
        run: npm run ci
