name: 'snyk'
on:
  push:
    branches: [main, develop]
  pull_request_review:
    branches: [main, develop]
  schedule:
    #        17:50 every Monday
    - cron: '50 17 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: '--sarif-file-output=snyk.sarif'
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'snyk.sarif'
